### ISSUE TITLE
Authenticate all API routes

### ISSUE THREAD

**Issue by clark-teeple** [KrisBraun/sanctuary-patient-api#11]
## Requirements
All MVP endpoints need to be authenticated, so the requirements are... do whatever is required to make all MVP endpoints authenticated after deciding which auth strategy we're going to use.

If we wanted to be super thorough, the POST messages endpoint could be restricted only to whatever kind of task we schedule for sending texts. 

Final requirement is to make a ticket for locking down the app once auth method is decided on.

### Google auth
Apparently all the people at Sanctuary who would be using this have google accounts, so this could be an easy way to authenticate. Possibly some privacy issues... Under normal commercial circumstances, we'd have to sign a BAA with google to be (HIPAA... not sure about Canadian equivalent) compliant. https://support.google.com/a/answer/3407054?hl=en

The other problem with Google is that... we don't want just anyone to make an account. Using the next option would let us create accounts and limit who gets to use the app.

### Email/pass w/ jwt
Not hard to do, keeps big bro google out, lets us control users, more annoying for users.

## Notes
I figured it would make the most sense to decide on auth strategy in the API first and then lock down the app once we have it figured out.

**Comment by iamstevedavis** [comment]
If everyone who has an account can see all the data, how is Google Auth supposed to work? Could someone give a little bit of insight into what the auth is supposed to cover? We might need to have a pre approved account system in place if everyone can see all the data and there is no differentiation between accounts.

**Comment by clark-teeple** [comment]
good point @iamstevedavis ... added to the ticket description.

**Comment by iamstevedavis** [comment]
It might be a good idea, if we are wanting to get this out the door, to just protect all the routes with an admin account and give them all that one login for now. It would serve the same purpose.

**Comment by clark-teeple** [comment]
Sounds good to me. @gingerich any objections?

**Comment by KrisBraun** [comment]
Added the client-side issue based on #14 here: https://github.com/KrisBraun/sanctuary-patient-app/issues/3

**Comment by iamstevedavis** [comment]
https://github.com/KrisBraun/sanctuary-patient-api/pull/14
